### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by SilverRainZ** [SrainApp/srain#110]
The current one: http://doc.srain.im/en/0.06.4/develop.html

Discussion record: [2018-08-21](http://irclog.silverrainz.me/srain/2018-08-21) [2018-08-22](http://irclog.silverrainz.me/srain/2018-08-22) 

- Code style (format, naming)
- Git workflow
  - Commit message
  - Branch name, tag name
  - Issue/PR templates, Issue/PR tag usage
  - Contribution process
- Document
  - Change log format
  - Release process
  - Code comments
- IRC rule

**Comment by SilverRainZ** [comment]
Code style
========

- 格式
  - 每行（含缩进）尽量不超过 80 个字符宽度（汉字以两字符计）
  - 四空格缩进，不使用 Tab
  - 提交的代码需经过 [clang-format](https://en.wikipedia.org/wiki/Include_guard) 格式化
- 注释
  - 对单句代码的注释使用 `//`
  - 对代码段落的注释使用 `/* */`
  - 文档注释使用 `/** **/` （其他细节待补，Doxygen 格式？）
  - 句首第一个单词首字符大写，注释只有一句时结尾不加标点，多句时使用标点符号
  - 注释（含缩进）每行不得超过 80 字符（汉字以两字符计），链接可以不折行
- 命名
  - 代码文件名全小写，以下划线分隔
  - 自定义类型名使用大驼峰命名法，按 模块名 + 类型名 命名，比如，Sui 模块下的 Window 控件的类型名为 `SuiWindow`，类型名不鼓励缩写，不允许使用非广泛使用的英文缩写
  - GObject 类型的相关命名遵循 [GType Conventions](https://developer.gnome.org/gobject/stable/gtype-conventions.html)
  - 宏使用全大写 + 下划线分割，和自定义类型相关的宏应以类型名为前缀，否则以模块名为前缀，宏不鼓励缩写，不允许使用非广泛使用的英文缩写
  - 函数名使用全小写 + 下划线分割，不对外导出 (`static`) 的函数无明确命名限制，和自定义类型相关的函数应以类型名为前缀，否则以模块名为前缀，不鼓励缩写，不允许使用非广泛使用的英文缩写
  - 变量名使用全小写 + 下划线
  - 鼓励局部变量和函数参数使用缩写，全局变量不鼓励缩写，结构体成员允许缩写
- 其他
  - 头文件使用  `__XXX_H`  形式的 [#include guard](https://en.wikipedia.org/wiki/Include_guard

**Comment by SilverRainZ** [comment]
Git workflow
==========

- Commit message
- Branch 只允许使用固定的 tag 和前缀，并以 `/` 分割，tag 和前缀只允许使用 alphanumeric + hyphen
  - 长期分支
    - `master` 主分支，下一版本的开发分支，需要尽量保证该分支可用，未完成的 feature 不允许 merge 到该分支，**不允许 owner 之外的人 force push** 
    - `dev/<version>` 某一版本的开发分支，从 `master` fork 而来，且不允许和 master 分叉，不需要保证该分支的可用性，版本发布后即删除，**允许但不鼓励 force push**
    - `dev/<name>` 维护者的个人开发分支，请随意处理
    - `stable/<version>` 大版本的稳定分支，与 master 可能分叉，该分支上只允许提交 bug fix 和较小的功能实现，**不允许 force push** 
  - 短期分支
    - `bugfix/<description>` bug 修复分支，merge 到目的分支后删除
    - `feature/<description>` 新功能开发分支，merge 到目的分支后删除
    - `refactor/<description>` 重构分支，merge 到目的分支后删除
  - `misc/<description>` 用于上面未覆盖到的各种情况的分支

**Comment by SilverRainZ** [comment]
Issue track 
========

- Issue 模板暂无
- Pull request 模板暂无
- Tag
  - 类型
    - `type-bug`
    - `type-cleanup`
    - `type-duplicate`
    - `type-improve`
    - `type-feature`
    - `type-help-wanted`
    - `type-invalid`
    - `type-question`
    - `type-todo`
    - `type-wontfix`
    - `type-need-details`
    - `type-need-discussion`
  - 模块
    - `mod-core`
    - `mod-irc`
    - `mod-ui`
    - `mod-config`
    - `mod-command`
    - `mod-decorator`
    - `mod-filter`
    - `mod-plugin`
    - `mod-lib`
    - `mod-doc`
    - `mod-i18n`
    - `mod-test`
    - `mod-script`
  - 平台
    - `os-linux`
    - `os-macos`
    - `os-windows`
  - 难度
    - `difficulty-hard`
    - `difficulty-medium`
    - `difficulty-easy`
  - 优先级
    - `priority-high`
    - `priority-normal`
    - `priority-low`

**Comment by ZWindL** [comment]
Git branch name '/' 后面的 <description> 有拼写规范吗？

**Comment by SilverRainZ** [comment]
之前的讨论结果是自由发挥，不要再次包含 `/` 即可。

**Comment by SilverRainZ** [comment]
现在 scope 是根据项目的不同模块划分的，比如 Sui Sirc Core 等，那如果我出于相同的目的更改了几个 scope 里面的代码，那么这个提交的 scope 该怎么写呢？

比如：https://github.com/SilverRainZ/srain/commit/0ac13129340446dbbfe8b3e3be6f2bca9cfbdbc8

@VOID001 @ZWindL

**Comment by ZWindL** [comment]
@SilverRainZ 创建多个提交？

**Comment by VOID001** [comment]
我同意 @ZWindL 的说法，我觉得如果一个提交的更改不是一个单位的话应该拆分成多个提交
