### ISSUE TITLE
Translation update and review

### ISSUE THREAD

**Issue by SilverRainZ** [SrainApp/srain#114]
- [x] Update original text
- [x] ru by @tim77 
- [x] zh_CN by @VOID001 

Anyone willing to contribute more translations?

**Comment by SilverRainZ** [comment]
@VOID001 Can you please update the current chinese translation? If you think the original english text is unreasonable, feel free to discuss with me and correct it.

Please work on branch `chore/translation-for-1.0`.

If you want to modify the original text, find its location in the code, edit it in place, then run `make install-po` to update it to po/pot file.

**Comment by VOID001** [comment]
got it， I will discuss the details with you if needed

**Comment by SilverRainZ** [comment]
2 week passed, any progess?

**Comment by VOID001** [comment]
more than half is done, but some details need to disscus

**Comment by VOID001** [comment]
I've marked the part I am uncertain or confusing using TODO mark, plz see the information inline
