### ISSUE TITLE
Srain SVG icon

### ISSUE THREAD

**Issue by SilverRainZ** [SrainApp/srain#120]

**Comment by SilverRainZ** [comment]
https://developer.gnome.org/hig/stable/icon-design.html.en

**Comment by SilverRainZ** [comment]
Use [Standard Icon Names](https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#names
- Send message icon: document-send
- Cancel message send icon: process-stop
- Users
  - User: user-available
  - ...
- Plugin: application-x-addon
- Goto bottom: go-bottom
- Goto last mentioned message: go-up
- Exit: application-exit
- Preference: preferences-system
- About: help-about
- Help: help-faq
- Server： network-server
- Channel: system-users
- Srain: start-here

**Comment by tim77** [comment]
Great update.
