### ISSUE TITLE
Implement more login method

### ISSUE THREAD

**Issue by SilverRainZ** [SrainApp/srain#122]
- [ ] ~~`pass`: Pass password in `<nickname>:<password>` by IRC `PASS` (server password) message, used in znc~~
- [x] `nickserv`: IRC `NICKSERV` message, it is not defined in RFC but implemented by some IRC server
- [x] `msg-nickserv` Send `PRIVMSG :identify <password>` to [IRC services](https://en.wikipedia.org/wiki/IRC_services) NickServ
- [x] `sasl-plain` [RFC 4616](https://tools.ietf.org/html/rfc4616)
- [ ] `sasl-external` [RFC 4422](https://tools.ietf.org/html/rfc4422)
- [x] `sasl-ecdsa-nist256p-challenge`

**Comment by SilverRainZ** [comment]
夏娜来订个 DDL 吧……

**Comment by VOID001** [comment]
等我考完考试我就有时间弄了．．现在真的是抽不出时间，具体情况 PM LA了

**Comment by SilverRainZ** [comment]
OK，那我先 unassign 了。

**Comment by VOID001** [comment]
I will then work on implementing the sasl extern authentication

**Comment by VOID001** [comment]
sasl won't be implemented, instead we implement ecdsa-nist256p-challenge, it's the auth method that used by weechat and other IRC clients.
