### ISSUE TITLE
When right click on the server buffer, the popup menu is not correct

### ISSUE THREAD

**Issue by VOID001** [SrainApp/srain#142]
![image](https://user-images.githubusercontent.com/6134883/47414010-8290c680-d7a2-11e8-931b-513fe37ee624.png)

In the picture above, I expected to see a channel popup menu, however I get a server popup menu.

**Comment by VOID001** [comment]
I clicked on SilverRainZ channel/user item, but the focus is still on the server buffer.

**Comment by SilverRainZ** [comment]
It is default behavior of GtkStack, I am not sure whether it can be change.

**Comment by VOID001** [comment]
I will dig into it

**Comment by VOID001** [comment]
我看了下 GtkListBox 貌似没有这种 hover event, 目前还是拿不到点击右键的时候所在的 Item

**Comment by VOID001** [comment]
Well I don't think button-press-event signal is enough to handle this situation. When right click on a unselected SuiSideBarItem, we don't have any way to get which SideBarItem the cursor is on. 
The "enter-notify-event" instead, it will be triggered each time the cursor enter the widget's window, we can wrap a GtkEventBox(a container with window and can emit the event mentioned above) and put the SuiSideBarItem into it. Thus we are able to get the enter-notify-event each time the cursor enter a specified SuiSideBarItem.

**Comment by SilverRainZ** [comment]
I mean connect the "button-press-event" on every created SuiSideBarItem (Item of side bar), but not a  whole SuiSideBar. When we right click SuiSideBarItem, we can get the correct SuiSideBarItem from the callback arguments.

**Comment by VOID001** [comment]
![image](https://user-images.githubusercontent.com/6134883/52158059-62d93a80-26cf-11e9-8ca7-be1e62ed8b90.png)
I see, but I've tested before, currently It seems that the button press event cannot be catched by the gtk debugger (I wonder the whether signal emits or not)

**Comment by SilverRainZ** [comment]
Done via https://github.com/SrainApp/srain/pull/353
