### ISSUE TITLE
The error check message is not easy to understand for human (?

### ISSUE THREAD

**Issue by VOID001** [SrainApp/srain#155]
![image](https://user-images.githubusercontent.com/6134883/52172447-4c53e180-27aa-11e9-866e-ee4617cde7d2.png)
Login method XX is set while field YY is unset.
This message is correct but much more seems like a debug message for dev, instead of a hint message for users

**Comment by SilverRainZ** [comment]
Yes, indeed, any better idea?

**Comment by VOID001** [comment]
A sample response:
You need to set the field %1$s in order to use login method %2$s.
