### ISSUE TITLE
sui_url_previewer cannot fetch the content when socks5 proxy is set in KDE system settings

### ISSUE THREAD

**Issue by VOID001** [SrainApp/srain#160]
Steps to reproduce:
1. set up the socks proxy in KDE System Settings
![pic](https://img.vim-cn.com/ff/cfc92ef042325aab4f6451e41292e0ed66b480.png)
2. Send a picture URL with srain
![pic](https://img.vim-cn.com/20/2466123a772f538c1439e045281e9c4f8bdd46.png)
3. Do not proxy the site and retry sending a picture with srain
![pic](https://img.vim-cn.com/03/6e529753d7bdf853a64f6c3593ca54b711bcc3.png)

I don't know whether the soup client is able to support the socks5 proxy, if it doesn't support, maybe we can fetch the content directly, if it support, we should figure out what option should be set to use the proxy

**Comment by VOID001** [comment]
Workaround ok. Now we force soup client fetch content directly without proxy. Future we will try to write custom proxy resolver
SOUP_SESSION_PROXY_RESOLVER is now set to NULL

**Comment by VOID001** [comment]
According to the [GIO Reference](https://developer.gnome.org/gio//2.56/GProxyResolver.html), the if we do not configure the SOUP_SESSION_PROXY_RESOLVER, it will use the default implementation, However I cannot figure out whether the default impl supports socks5, socks5a schema. But I found that glib-networking has a libproxy module that (likely to) support these schema https://gitlab.gnome.org/GNOME/glib-networking/blob/master/proxy/tests/libproxy.c

**Comment by VOID001** [comment]
@SilverRainZ After I change the proxy Scheme `SOCKS5` to `socks5` everything goes well :P 
I think maybe I should file a PR to libproxy (

**Comment by SilverRainZ** [comment]
@VOID001 So we consider it is a upstream issue?

**Comment by VOID001** [comment]
Yes, but I think first find out the upstream bug part is necessary, so let's keep this issue open for about a week :P

**Comment by SilverRainZ** [comment]
16 weeks passed : )

**Comment by VOID001** [comment]
:(
