### ISSUE TITLE
Fedora RPM package

### ISSUE THREAD

**Issue by tim77** [SrainApp/srain#173]
#### Not issue, just info:

📦 Srain RPM package in [COPR](https://copr.fedorainfracloud.org/coprs/atim/srain/)

How to install:
```shell
sudo dnf copr enable atim/srain -y && sudo dnf install srain -y
```
Run:
```
srain
```
🙏🏻

**Comment by SilverRainZ** [comment]
Thank you for your package, I wll update it to https//doc.srain.im/en/latest/install.html#distribution-packages soon.

**Comment by tim77** [comment]
Now in official Fedora repos and ready for testing:

[Fedora 29](https://bodhi.fedoraproject.org/updates/srain-1.0.0-0.2.rc3.fc29)
[Fedora 30](https://bodhi.fedoraproject.org/updates/srain-1.0.0-0.2.rc3.fc30)

**Comment by SilverRainZ** [comment]
When will these two packages become stable?

**Comment by tim77** [comment]
Until someone give them at least 1 karma (+1) or need to wait 7 days for current stable Fedora release (29) or 3 days for Fedora beta (30). But Bodhi is become terribly slow nowadays and there is the plans to rewrite it from Python. :)

Today i pushed for F29 so now its all on Bodhi. It can takes few minutes or 1 day.

**Comment by SilverRainZ** [comment]
Documented to http://doc.srain.im/en/latest/install.html#fedora

**Comment by SilverRainZ** [comment]
I can not find srain on https://apps.fedoraproject.org/packages/s/srain , @tim77 any idea?

**Comment by tim77** [comment]
@SilverRainZ this is forever buggy Fedora infra and this is well known bug. I personnay suggest replace this home package page with this one: https://src.fedoraproject.org/rpms/srain

As you can see latest version always packaged. :)
