### ISSUE TITLE
Use default button relief in HeaderBar

### ISSUE THREAD

**Issue by bellegarde-c** [SrainApp/srain#200]
Srain looks out of place with Adwaita, you should not force button relief in headerbar.

regards,

**Comment by SilverRainZ** [comment]
Can you please give me a screenshot? I found the header bar and the side bar are not aligned when using Adwaita, but it seems not caused by button relief.

**Comment by bellegarde-c** [comment]
Here Srain headerbar, relief off and non symbolic icons:

![srain](https://user-images.githubusercontent.com/57196916/75662266-187a1280-5c6f-11ea-9008-dc332b8735e1.png)

Here a GNOME app headerbar, relief default and symbolic icons:

![gnome](https://user-images.githubusercontent.com/57196916/75662339-334c8700-5c6f-11ea-8343-84cf8fafdf6c.png)

**Comment by SilverRainZ** [comment]
Get it, I will respect the default button relife. But I am still no idea about why Srain uses a non-symbolic icons.

**Comment by bellegarde-c** [comment]
You need to use "iconname-symbolic" instead of "iconname".

Bad news, Elementary choosed "iconname" by default in headerbar so depends on what desktop you are targetting :-1:

**Comment by SilverRainZ** [comment]
I use GtkMenuButton whose icon-name is determinate by GTK internal by default.

> The GtkMenuButton widget can hold any valid child widget. That is, it can hold almost any other standard GtkWidget. The most commonly used child is GtkImage. If no widget is explicitely added to the GtkMenuButton, a GtkImage is automatically created, using an arrow image oriented according to “direction” or the **generic “open-menu-symbolic” icon if the direction is not set.**

I tried set the  “direction” to none, it does't work as expect.

For other icons, I afaid that no all user has a "symbolic" icon theme installed.

**Comment by bellegarde-c** [comment]
All users should have symbolic icons if GTK is installed.

```
# pacman -R adwaita-icon-theme
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing adwaita-icon-theme breaks dependency 'adwaita-icon-theme' required by gtk3
```

**Comment by bellegarde-c** [comment]
Here, settings direction to none on GtkMenuButton give me “open-menu-symbolic” .

**Comment by SilverRainZ** [comment]
@bellegarde-c I found that I use a custom GtkImage in the GtkMenuButton, remove it and anything goes well.

I open a PR to follow your nice suggestion, please take a look.
