### ISSUE TITLE
znc login support

### ISSUE THREAD

**Issue by ZachBacon** [SrainApp/srain#209]
Didn't exactly see any documentation for logging into a znc, tried to figure it out but I'm rather lost on it at the moment, and passing /quote to manually logging in a znc instance but the client didn't understand passing /quote saying that it was an unknown command.

**Comment by SilverRainZ** [comment]
ZNC is also an IRC server so Srain can login as login any IRC server.
If you use quote for PASS command(`/quote PASS xxxx`), you can fill you password at the "Advanced Mode" -> "Password" field.

**Comment by ZachBacon** [comment]
Except that doesn't work, that was my original thought, znc's method is typically /quote pass username:password 

Or sometimes /quote pass username/server:password

**Comment by ZachBacon** [comment]
never mind on that, I honestly didn't get it till now, happens when I don't sleep enough. Working well now.

**Comment by SilverRainZ** [comment]
Please refer to: https://doc.srain.im/en/latest/faq.html#why-can-t-i-login-to-my-znc-server
