### ISSUE TITLE
option to disable parting messages

### ISSUE THREAD

**Issue by muralikodali** [SrainApp/srain#210]
is there any option to disable display of leaving users (which are annoying sometimes with whole screen filled up with theses messages) ?

**Comment by SilverRainZ** [comment]
No yet, for now you can write a regex to filter them.

For example:

```
/pattern add filter-part ^\w+ has left: .*$
/filter filter-part
```

works in most cases.

**Comment by muralikodali** [comment]
thanks for your suggestion. providing the option in preferences is requested for removing clutter of joinings, partings and other messages.

**Comment by Justinzobel** [comment]
So this needs to be done for each channel with a unique filter name for each?

**Comment by SilverRainZ** [comment]
No, it effects all channel in same server.

**Comment by Justinzobel** [comment]
Ah excellent.
