### ISSUE TITLE
Cannot connect to ZNC relay

### ISSUE THREAD

**Issue by Justinzobel** [SrainApp/srain#212]
Cannot connect to ZNC relay. Need the ability to run /quote PASS username:password and it sends to the server to authenticate.

**Comment by ZachBacon** [comment]
@Justinzobel so in advance tab, (and I ran into this issue, so trust me on this, you know me :P) in the password you need to use username:password into that dialog.

**Comment by Justinzobel** [comment]
Thanks that works @ZachBacon

**Comment by SilverRainZ** [comment]
Duplicated with #209

**Comment by Justinzobel** [comment]
Would be great to have some documentation around it.

**Comment by SilverRainZ** [comment]
@Justinzobel Please see: https://doc.srain.im/en/latest/faq.html#why-can-t-i-login-to-my-znc-server

**Comment by Justinzobel** [comment]
Thanks!
