### ISSUE TITLE
[placeholder] packaging for Debian

### ISSUE THREAD

**Issue by okias** [SrainApp/srain#221]
I'm making this as placeholder.

Would be nice having srain packaged for Debian (== all derivates, including PureOS for mobiles).

In worst case scenario where no experienced Debian packager stepup, I'll try to do it in few weeks.

**Comment by SilverRainZ** [comment]
Thank you, @tomac4t has written [this](https://github.com/SrainApp/srain-contrib/tree/master/pack/debian) fews days ago, should be helpful for you.

**Comment by okias** [comment]
send a pull request with modernization of debian build stuff and also when all this stuff gets fixed, I can ask maintainers to accept it into Debian! :)

**Comment by SilverRainZ** [comment]
@okias Should I reslove **all** issues to make this package accepted by debian?

**Comment by okias** [comment]
All solvable :) it's extra strict check

**Comment by SilverRainZ** [comment]
Srain side:

- [ ] E: srain: possible-gpl-code-linked-with-openssl
    - libecdsaauth use openssl...
- [ ] W: srain: binary-without-manpage usr/bin/srain
    - We can generate man page from current doc
- [ ] I: srain: hardening-no-fortify-functions usr/bin/srain
    - I am no idea about how to fix it
- [x] I: srain: spelling-error-in-binary usr/bin/srain Closeing Closing
- [x] I: srain: spelling-error-in-binary usr/bin/srain Unspported Unsupported
- [x] I: srain: spelling-error-in-binary usr/bin/srain channnel channel
- [x] I: srain: spelling-error-in-binary usr/bin/srain channnels channels
- [x] I: srain: spelling-error-in-binary usr/bin/srain opiton option
- [x] I: srain: spelling-error-in-binary usr/bin/srain recieved received
- [x] I: srain: spelling-error-in-binary usr/bin/srain vaule value
- [ ] I: srain source: testsuite-autopkgtest-missing
    - We may add some test in future, but not now :-(
- [ ] W: srain: raster-image-in-scalable-directory usr/share/icons/hicolor/scalable/apps/im.srain.Srain.png
    - I will fix it soon

Debian side:

- Menu issues: I know nothing about this menu file, it causes a lot of warning:
    - [ ] W: srain source: changelog-should-mention-nmu
    - [ ] W: srain: command-in-menu-file-and-desktop-file srain usr/share/menu/srain:2
    - [ ] W: srain: menu-item-creates-new-section Applications/Network usr/share/menu/srain:2
    - [ ] W: srain: menu-item-needs-tag-has-unknown-value x11|text|vc|wm usr/share/menu/srain:2
    - [ ] W: srain source: source-nmu-has-incorrect-version-number 1.0.1-1
- [ ] W: srain source: inconsistent-appstream-metadata-license data/srain.appdata.xml (fsfap != gpl-3.0+)
    - The data/srain.appdata.xml is licensed under FSFAP but not GPL-3.0+, It should be mentioned in debian/copyright
- [ ] X: srain source: debian-watch-does-not-check-gpg-signature:
    - It is not an issue IMO.

@okias I list all warning here, most on the srain side is slovable. Can you please see the warning on debian side?

**Comment by okias** [comment]
Thanks. Fix what you can.
```E: srain: possible-gpl-code-linked-with-openssl ``` must be solved for sure, but no experience with this one.
```NMU``` issues is because I put myself into changelog (it doesn't matter, can be removed with another merge.
```hardening``` probably that you should have C option to enable some https://access.redhat.com/blogs/766093/posts/1976213 Fortify, no much insight into your app (sorry, working right now on different stuff), but you could make some option to enable fortifying your code (due fact that some people prefer performance and lower memory impact. But due fact that IRC is includes handing data from internet it would be nice to be extra sure Srain is "safe-app" ;)
```menu stuff``` look into some GNOME application, they're have it usually correctly I suppose. GNOME- follow most standarts.

**Comment by SilverRainZ** [comment]
@okias For OpenSSL issue, we can add execption declaration to Srain's license as [deluge does](https://github.com/deluge-torrent/deluge/blob/develop/LICENSE#L4).

**Comment by okias** [comment]
probably easiest solution. Also if you use only some small portion of OpenSSL you could consider some more lightweight/modern library, but that's more challenging solution :P

**Comment by okias** [comment]
Licensing -> for example Transmission which also links with OpenSSL solves it like this in:
https://github.com/transmission/transmission/blob/master/COPYING

so probably adding something like 
```
In addition, linking to and/or using OpenSSL is allowed.
```
in some meaningful place into your LICENSE could be fulfilling.

**Comment by okias** [comment]
All menu issues are solved by https://github.com/SrainApp/srain-contrib/pull/6

**Comment by okias** [comment]
@SilverRainZ hey hey, finally switched to Debian as daily driver and hitting that Licence issue, any chance to put something like

> In addition, linking to and/or using OpenSSL is allowed.

into licence? It's only error I get currently from Debian lintian.

**Comment by SilverRainZ** [comment]
https://ftp-master.debian.org/new/srain_1.3.0-1.html
