### ISSUE TITLE
make fails on Mojave after installing dependencies 

### ISSUE THREAD

**Issue by alex-strafalogea** [SrainApp/srain#237]
Seems like I cannot execute make correctly after installing the dependencies 

`srain on  master
❯ make
mkdir -p /Users/xxx/srain/build
make -C data resources
make[1]: Nothing to be done for `resources'.
make -C src
make /Users/xxx/srain/build/srain.out
Package openssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `openssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'openssl' found
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gcc -std=gnu99 -O2 -Wall -Iinc -Wno-deprecated-declarations -D PACKAGE='"srain"' -D PACKAGE_NAME='"Srain"' -D PACKAGE_VERSION='"1.0.2"' -D PACKAGE_BUILD='"-n -git@0.1377.c922b9d"' -D PACKAGE_APPID='"im.srain.Srain"' -D PACKAGE_AUTHOR='"Shengyu Zhang"' -D PACKAGE_EMAIL='"i@silverrainz.me"' -D PACKAGE_DESC='"Modern IRC client written in GTK."' -D PACKAGE_WEBSITE='"https://srain.im"' -D PACKAGE_DATA_DIR='"/usr/local/share"' -D PACKAGE_CONFIG_DIR='"/etc"' -D PACKAGE_COPYRIGHT_DATES='"2016 - 2020"' -ggdb -I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/Cellar/gtk+3/3.24.17/include/gtk-3.0 -I/usr/local/Cellar/glib/2.64.2/include/gio-unix-2.0 -I/usr/local/Cellar/cairo/1.16.0_3/include/cairo -I/usr/local/Cellar/libepoxy/1.5.4/include -I/usr/local/Cellar/pango/1.44.7/include/pango-1.0 -I/usr/local/Cellar/fribidi/1.0.9/include/fribidi -I/usr/local/Cellar/harfbuzz/2.6.4/include/harfbuzz -I/usr/local/Cellar/graphite2/1.3.14/include -I/usr/local/Cellar/atk/2.36.0/include/atk-1.0 -I/usr/local/Cellar/cairo/1.16.0_3/include/cairo -I/usr/local/Cellar/pixman/0.38.4/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/gdk-pixbuf/2.40.0/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/glib/2.64.2/include -I/usr/local/Cellar/glib/2.64.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.64.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.44/include -I/usr/local/Cellar/libconfig/1.7.2/include -I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/Cellar/libsoup/2.70.0/include/libsoup-2.4 -I/usr/local/Cellar/libpsl/0.21.0_2/include -I/usr/local/Cellar/glib/2.64.2/include -I/usr/local/Cellar/glib/2.64.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.64.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.44/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2   -c config/manager.c -o /Users/astrafalogea/srain/build/manager.o
In file included from config/manager.c:31:
inc/config/config.h:23:10: fatal error: 'libsecret/secret.h' file not found
#include <libsecret/secret.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [/Users/xxx/srain/build/manager.o] Error 1
make[1]: *** [default] Error 2
make: *** [default] Error 2`

Let me know if you need more info to confirm or fix this.

**Comment by SilverRainZ** [comment]
Try ` brew install libsecret`?

**Comment by alex-strafalogea** [comment]
Nice, that did the trick, now forward with the next one.

`inc/libecdsaauth/keypair.h:24:10: fatal error: 'openssl/ec.h' file not found
#include <openssl/ec.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[2]: *** [/Users/xxx/srain/build/app_irc_event.o] Error 1
make[1]: *** [default] Error 2
make: *** [default] Error 2`

I knew I had openssl installed via brew on mac, so I'm stuck now.

`❯ brew install openssl
Updating Homebrew...
Warning: openssl@1.1 1.1.1f is already installed and up-to-date
To reinstall 1.1.1f, run `brew reinstall openssl@1.1``

Any ideas?

**Comment by SilverRainZ** [comment]
It seem a mac specific issue, try `brew link openssl --force`? I have no a macOS environment, google "macos openssl dev" may be helpful to you.

**Comment by alex-strafalogea** [comment]
Nice, another step forward. Thanks for helping out with this and sorry for my laziness in google-ing.

Now at the last step when trying to `sudo make install` I get the following every time:

`install -v -Dm755 "/Users/xxx/srain/build/srain.out" "/usr/local/bin/srain"
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install-bin] Error 64
`

**Comment by SilverRainZ** [comment]
:'( Try: https://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities

**Comment by SilverRainZ** [comment]
/me have to sleep, will reply tomorrow.

**Comment by SilverRainZ** [comment]
Any progress?

**Comment by ZachBacon** [comment]
You shouldn't force a link for openssl, in homebrew using PKG_CONFIG_PATH and point it to /usr/local/lib/pkgconfig should be enough. The reason you don't want to force a link is due to it could break system ssl.

**Comment by ZachBacon** [comment]
Worst comes to worse, what I could do is provide binary builds of srain on my hackintosh PC once I fix the current build issue I'm experiencing.

**Comment by SilverRainZ** [comment]
@ZachBacon Thanks for the alarm. If submit srain to homebrew, can we get this thing more simple?

**Comment by ZachBacon** [comment]
We could do that, but I'm thinking more of making a proper app bundle that's downloadable for those that don't use homebrew or anything like it.

**Comment by SilverRainZ** [comment]
We can attach a macOS package to github release? I am not sure whether it need rebuild when macOS has a version upgrade.

**Comment by ZachBacon** [comment]
It shouldn't. An app bundle has all dependencies included, it's kinda like snaps on Linux in a manner of speaking. My own project does builds for Mac, windows and Linux, so I have a bit of experience there.

But yeah it's self contained, the only time it wouldn't work is if macOS did something entirely stupid and deprecated their underlying toolkit that gtk3 currently uses. Which I don't foresee for some time, and even then if they did, they at least come up with options ahead of time for developers to target. So it's all good on our end.

**Comment by SilverRainZ** [comment]
> I have a bit of experience there.

That is so helpful, can you help Srain to make such an app bundle?

**Comment by ZachBacon** [comment]
> > I have a bit of experience there.
> 
> That is so helpful, can you help Srain to make such an app bundle?

I can indeed. I'll look into it as soon as I fix up my hackintosh setup. I made a mistake on my boot partition and I may need to reinstall sadly but I can at least on my Linux box begin the process of hooking up the needed bits to make the bundle for macOS and send a pr

**Comment by alex-strafalogea** [comment]
> Any progress?

I dint really want to mess up with the build tools on my Mac un after what I've read on SO.

I can help you guys debug on MacOS, let me know if you need any help for new solution or testing

**Comment by ZachBacon** [comment]
@alex-strafalogea I'm hoping to have something soon. I can't give a firm date as I need to test locally before anything else and even then it'll be test builds so once I get those posted here, I'll be relying on you to test.

**Comment by SilverRainZ** [comment]
@ZachBacon  any progress?
