### ISSUE TITLE
SASL External

### ISSUE THREAD

**Issue by travankor** [SrainApp/srain#246]
Can you add support for the SASL external (rfc 4422)?

Refs:
https://tools.ietf.org/html/rfc4422
https://ircv3.net/specs/extensions/sasl-3.1

**Comment by SilverRainZ** [comment]
Sure, I will try to implement it.

**Comment by SilverRainZ** [comment]
Purpose to use https://github.com/cyrusimap/cyrus-sasl

- SASL client guide: https://www.cyrusimap.org/sasl/sasl/developer/programming.html#client-only-section
- Manpage: https://www.cyrusimap.org/sasl/sasl/manpages.html
