### ISSUE TITLE
reproducible build failing

### ISSUE THREAD

**Issue by okias** [SrainApp/srain#265]
I'm trying to pass Debian repro build and it seems that some builds are different, uploading here log including `diffoscope`, maybe you'll see more than I do now
[raw_log.txt](https://github.com/SrainApp/srain/files/5263487/raw_log.txt)

**Comment by SilverRainZ** [comment]
:'( I have no idea about it.

**Comment by SilverRainZ** [comment]
I just port our build system to meson, can you please have a try?

**Comment by SilverRainZ** [comment]
Closing due to age.
