### ISSUE TITLE
[FEATURE REQUEST] /clear command

### ISSUE THREAD

**Issue by AlbinoGeek** [SrainApp/srain#268]
## Summary

I've been using srain for quite a while on Fedora (`1.1.1`) and can't help but be plagued with the near unlimited memory usage of this GTK+ application, considering there's no command (or menu item) to clear a channel's past messages from the screen!

**Comment by SilverRainZ** [comment]
No yet :-), It is easy to implement one  and I will it soon.

For now,  you can `/part` and `/join` again.
