### ISSUE TITLE
[FEATURE REQUEST] Font Size?

### ISSUE THREAD

**Issue by AlbinoGeek** [SrainApp/srain#272]
Would it be possible to change the font size of the application? Either via `Ctrl +` or `Ctrl -` -- or via the configuration file? Likewise, can I change or override the font name/style being used within the application?

**Comment by SilverRainZ** [comment]
Sorry for reply so late.

Yes, is possible, like other GTK application, you can change the system-level font setting or add custom CSS to srain's [theme](https://github.com/SrainApp/srain/blob/master/data/themes/default-min.css).

See also https://developer.gnome.org/gtk3/stable/chap-css-properties.html
