### ISSUE TITLE
[UI Problem] When a message is selected, the font in right-click menu will change color and be hard to read.

### ISSUE THREAD

**Issue by WhiredPlanck** [SrainApp/srain#275]
Before selecting:

![图片](https://user-images.githubusercontent.com/47623588/99895906-684dad80-2cc6-11eb-8612-37613b927197.png)

After selecting:

![图片](https://user-images.githubusercontent.com/47623588/99895918-903d1100-2cc6-11eb-9413-e10b1c12b9c2.png)

And the font color of the last 3 items in the selected message's right-click menu is white, which is as same as the menu background color.

**Comment by SilverRainZ** [comment]
What GTK theme are you using?

**Comment by whriedplanck** [comment]
> What GTK theme are you using?

Arc, Arc-lighter.

**Comment by SilverRainZ** [comment]
复现了，我找时间看看。

**Comment by whriedplanck** [comment]
> 复现了，我找时间看看。

好的，感谢 ～！

**Comment by SilverRainZ** [comment]
奇怪……今天复现不了了。

**Comment by SilverRainZ** [comment]
No response, close it, please reopen when you encounter this issue again.
