### ISSUE TITLE
dunst no notification 

### ISSUE THREAD

**Issue by danrobi11** [SrainApp/srain#281]
I dont get any notification when theres new message in rooms. I do have 1 notification in dunst when the server connect at launch. After that nothing.

srain v1.1.2-git@0.1.ab44777

```
    chat =
    {
        notify = true              
        notify-all = true            

```

**Comment by SilverRainZ** [comment]
Thanks for reporting.

I am dunst user too but I haven't encountered this issue. Are you window manager user and do you always let srain shown on your workspace? If so, can you please run srain from terminal to see if there is any log?

**Comment by danrobi11** [comment]
@SilverRainZ 

I receive notifications from the server channel login/logout. But I receive nothing from any #channels #srain etc.

Srain 1.1.2-git@0.1.ab44777
OS: MX 19.3 (patito feo) x86_64
SysV init version: 2.93
Debian GNU/Linux 10 (buster)
Kernel: 4.19.0-9-amd64
Xorg v1:7.7+19
WM: Spectrwm   

Thats the output so far. If more shows up, I'll come post:

```
$ srain
[WARN irc_event_cap] Unknown capability: 

** (srain:13054): WARNING **: 07:09:56.023: (core/message.c:82):srn_message_new: code should not be reached

** (srain:13054): WARNING **: 07:09:56.055: (core/message.c:82):srn_message_new: code should not be reached

** (srain:13054): WARNING **: 07:09:56.111: (core/message.c:82):srn_message_new: code should not be reached

** (srain:13054): CRITICAL **: 07:09:56.140: irc_event_mode: assertion 'chat_user' failed

** (srain:13054): WARNING **: 07:09:56.150: (core/message.c:82):srn_message_new: code should not be reached

** (srain:13054): WARNING **: 07:09:56.407: (core/message.c:82):srn_message_new: code should not be reached

** (srain:13054): CRITICAL **: 07:09:56.456: irc_event_mode: assertion 'chat_user' failed

** (srain:13054): CRITICAL **: 07:09:56.459: irc_event_channel_notice: assertion 'chat_user' failed

** (srain:13054): CRITICAL **: 07:09:56.460: irc_event_mode: assertion 'chat_user' failed

** (srain:13054): CRITICAL **: 07:09:56.463: irc_event_mode: assertion 'chat_user' failed

** (srain:13054): WARNING **: 07:09:56.468: (core/message.c:82):srn_message_new: code should not be reached
```

**Comment by danrobi11** [comment]
got this new output:
```(srain:13054): CRITICAL **: 07:51:50.336: srn_server_user_free: assertion 'g_list_length(self->chat_user_list) == 0' failed```

I noticed that I do have dunst notification when its from private chat (dm).

**Comment by SilverRainZ** [comment]
:( Unfortunately these information are nothing to do with the notification.

I see you set `notify-all = true`, I am sorry to tell you this feature is not implemented yet, see  :'( #167 

Can you receive notification when someone exactly **mention** you?

**Comment by danrobi11** [comment]
> this feature is not implemented yet

Ok I see. 

> Can you receive notification when someone exactly mention you?

Yes.

**Comment by SilverRainZ** [comment]
So, it is no a BUG (or a BUG of document lol)
