### ISSUE TITLE
Ability to save (export) parts of a discussion as a plaintext log file

### ISSUE THREAD

**Issue by nekohayo** [SrainApp/srain#282]
Basically the same wish as in https://gitlab.gnome.org/GNOME/fractal/-/issues/165

xchat-gnome had this feature but it was broken (gave me garbled files 9 out of 10 times), Hexchat has this feature (and it works!), and I would want to see it happen in Srain if I were to consider as a new day-to-day IRC client.

**Comment by SilverRainZ** [comment]
I think we already implemented it? please see: https://doc.srain.im/en/latest/misc.html#chat-logs
