### ISSUE TITLE
Cannot login via NickServ, getting error "You need to set field password to use login method msg-nickserv"

### ISSUE THREAD

**Issue by YgtOz** [SrainApp/srain#284]
I am editing the config file and I want to set the login to msg-nickserv but I have no idea where I should place the password string. I tried to place it in the freenode server under the addresses array, I tried to set it in the login brackets (where you set the login method), but I cannot figure out the syntax for entering the password. Thank you for reading.

edit: Setting login method to none and trying to auto-run a message to NickServ also gives an error. Furthermore I need help on configuring SASL as an alternative.

**Comment by SilverRainZ** [comment]
Hello, For security reasons, passwords are stored by dbus secret service(gnome-keyring, kwallet) but not configuration file, and this lead to inconvenient to use, I will improve this in future.

For now, you should:

0. Make sure you have a running dbus secret service
1. Keep your login config unchangd (msg-nickserv or anyone you like)
2. Remove the server from "auto-connect" list
3. Open srain, it will show you a login UI, switch to "Advanced Mode", select the server
4. You will found the login method combo box is set to the one you wish, but the password is empty
5. Enter you password, check "remember password"
6. Add back the server to the "auto-connect" list, anything should be well now.

**Comment by YgtOz** [comment]
Thank you! I was able to log in as I wanted through the Advanced Mode.

**Comment by milisarge** [comment]
maybe it can be considered as another less secure way:

```
server =
{
    auto-join = ["#abc","#def"]
    auto-run = ["/msg nickserv identify mypassword"]
```
