### ISSUE TITLE
In the sidebar, servers are not kept separate from channels, and cannot be hidden

### ISSUE THREAD

**Issue by nekohayo** [SrainApp/srain#286]
The current sidebar is non-hierarchical (i.e. a listview instead of a treeview, it seems) and the servers are put there with the same sort of importance as channels.

* I don't really care to see servers there. Might be nice to have a togglebutton with the ability to hide them (and thus only show channels)
* Servers are alphabetically sorted with channels... so if you join gimpnet, then join channels "#gnome-hackers" and channel "#epiphany", epiphany will show above GIMPnet, which doesn't make much visual sense. If the servers are shown, I would expect channels to be grouped under the same server.

**Comment by SilverRainZ** [comment]
Hello nekohayo.

1. non-hierarchical is a feature /o/
2. Yes most people does not care about servers, I wil add an option to hide it.

**Comment by SilverRainZ** [comment]
After the aboved PR merged, You can use the "Toggle server visibity" button to hide servers.

**Comment by titibandit** [comment]
Hey,
that would also be nice to be able to toggle the server visibility using the config file as well.

**Comment by SilverRainZ** [comment]
> Hey, that would also be nice to be able to toggle the server visibility using the config file as well.

@titibandit Can you please open a issue for this?

**Comment by titibandit** [comment]
done!
