### ISSUE TITLE
Small installation glitches in 1.2.0

### ISSUE THREAD

**Issue by lgbaldoni** [SrainApp/srain#290]
An empty `meson.build` file is installed with the themes and `im.srain.Srain.Red.png` is actually 128x123 instead of 128x128 as per freedesktop specs.

**Comment by lgbaldoni** [comment]
I also add that the appstream dependency is not checked and on older systems it produces [this](https://github.com/SrainApp/srain/files/6056571/srain_appstream_leap152.txt). But this might be distro-specific, I don't know enough about the matter.

**Comment by SilverRainZ** [comment]
> I also add that the appstream dependency is not checked and on older systems it produces this. But this might be distro-specific, I don't know enough about the matter.

I never meet this on Arch or Debian, and also doesn't know why appstream is needed here. so let it keep unchanged for now.
