### ISSUE TITLE
issues with custom theme

### ISSUE THREAD

**Issue by MissLav** [SrainApp/srain#291]
here we have it looking normal in adwaita dark
![image](https://user-images.githubusercontent.com/51702517/110846731-bdabcb80-8271-11eb-874c-dfd421a16617.png)

and here we have it with my custom oomox theme
![image](https://user-images.githubusercontent.com/51702517/110846988-fc418600-8271-11eb-85cb-850c6d1529cc.png)

this doesn't happen for any other program I use

example of a few programs
![image](https://user-images.githubusercontent.com/51702517/110847341-6d813900-8272-11eb-9a8b-09c591d18529.png)

**Comment by MissLav** [comment]
made an issue with the theme making software as well
https://github.com/themix-project/oomox/issues/369

**Comment by SilverRainZ** [comment]
GTK theme doesn't have a "dark" property, so srain doesn't know oomox is a dark theme, you can manually set `gtk-application-prefer-dark-theme=1` in `~/.config/gtk-3.0/settings.ini`.

**Comment by sodomon2** [comment]
Hi @MissLav I have the same problem since I use dracula-theme and to avoid it I have to run the srain from a `root console` or with `make run` :/

Here is a screenshot

![screenshot](https://i.imgur.com/ZyTRFiQ.png)

**Comment by SilverRainZ** [comment]
@sodomon2 Please see what I said aboved.

**Comment by actionless** [comment]
when you observing a GTK StyleContext of some widget (Window itself, or, let's say, some Button) it have background and foreground

if foreground is darker than background then it's a light area (and the opposite)

it's a bit naive to assume what al the theme gonna be all-light or all-dark, as it could be theme with dark headerbar and light windows, or all dark but with light buttons, etc
