### ISSUE TITLE
Srain won't read password in config file

### ISSUE THREAD

**Issue by VMGuy23** [SrainApp/srain#295]
Srain does not see my pasword, it is in 
server = { <here>, user = { <here>, login = { <here> } } }
server-list = ( { <here>} )
It is listed as 'password = "<my password>"'
on startup, it says it cannot add the network because the password feild needs to be filled.

**Comment by SilverRainZ** [comment]
Yes, for security reason, password is from dbus secret service, so srian won't read  it from configuration file.

You should have gnome-keyring or kwallet (maybe) installed, #284 may be helpful.

**Comment by VMGuy23** [comment]
Yeah, I checked "remember password" and it worked, removing password from config now
