### ISSUE TITLE
Close button is in the wrong place on elementary OS (or any distro with controls on the left?)

### ISSUE THREAD

**Issue by ryanrms** [SrainApp/srain#296]
As you can see, the close button is on the right hand side of the channels pane, when it should be on the far left.  I have included a picture of a properly functioning application overlayed on top of the Srain window so you can see what it's supposed to be.

Button order on elementary is "close:maximize" with close on the far left, and maximize on the far right, with the title and contents supposed to be in the middle.  Hope I can help diagnose and test this issue for you guys.

![Screenshot from 2021-04-03 20-14-02](https://user-images.githubusercontent.com/2936638/113496722-ae5b1f00-94b9-11eb-8047-25f6923e7c9f.png)

edit: I should note that this is version 1.20, I can install the git version to see if there's any change.

**Comment by SilverRainZ** [comment]
Hello, this is because srain use two header bars when CSD enabled, disable CSD (set  `csd = false`) would help.
