### ISSUE TITLE
no exe to run in the windows build

### ISSUE THREAD

**Issue by therock247uk** [SrainApp/srain#301]
No .exe in the package srain-1.2.2-mingw64

**Comment by SilverRainZ** [comment]
Can you please try https://github.com/SilverRainZ/srain/releases/tag/1.2.1-test6 ?

The exe is included but I am not sure whether it works, I have not a window environment to test it.

**Comment by therock247uk** [comment]
no srain.exe still

**Comment by SilverRainZ** [comment]
https://github.com/SrainApp/srain/releases/tag/1.2.1-windows
