### ISSUE TITLE
[Help Wanted] Clicking on URL fails to open helper program

### ISSUE THREAD

**Issue by metaperl** [SrainApp/srain#307]
Running this release:
https://github.com/SrainApp/srain/releases/tag/1.2.1-windows

![srain_WvWzK0k0YY](https://user-images.githubusercontent.com/21293/117469900-36529f80-af24-11eb-9460-95305dc947e0.png)

**Comment by SilverRainZ** [comment]
Can you please try https://github.com/SilverRainZ/srain/releases/download/1.2.1-test8/srain-1.2.1-test8-mingw64.zip ?

**Comment by SilverRainZ** [comment]
Sign, for the second problem, I think the IRC server use a non-UTF-8 encoding, you specified prefered encoding via "encoding" opitons in server block, see https://doc.srain.im/en/latest/config.html#all-configurable-items

**Comment by smaragdus** [comment]
@SilverRainZ 

Thanks for the explanation. By the way, do you plan to create GUI preferences for configuration of Srain in the future releases?

**Comment by SilverRainZ** [comment]
Yes, it is in plan, comes with GTK4 version.

> @SilverRainZ
> 
> Thanks for the explanation. By the way, do you plan to create GUI preferences for configuration of Srain in the future releases?

**Comment by SilverRainZ** [comment]
I am not longer use Windows anymore, if anyone want to fix this, feel free to file a PR.

**Comment by SilverRainZ** [comment]
@lifeibiren 这个有空的时候也能看下么（
