### ISSUE TITLE
用户列表中的用户不可见

### ISSUE THREAD

**Issue by inoton** [SrainApp/srain#319]
该问题仅出现在 srain 1.2.3 ，退回 1.2.2 后问题消失。  
当配置文件中 `show-user-list = false`  ，启用应用并在菜单中调出用户列表，用户列表**有很大的几率**无法显示用户在线人数，同时列表中用户不可见。  
  
<img src="https://raw.githubusercontent.com/inoton/Bright/main/srain1.png"  width="60%" height="60%" />
<img src="https://raw.githubusercontent.com/inoton/Bright/main/srain2.png"  width="60%" height="60%" />

**Comment by SilverRainZ** [comment]
I think it may caused by #316  :'(

**Comment by inoton** [comment]
喜闻 srain 1.2.4 已发布， 期待 fedora 安装包 😄

**Comment by SilverRainZ** [comment]
@inoton 这个问题只修了一半……用户不会不可见，但是 icon 会丢掉。

**Comment by inoton** [comment]
> @inoton 这个问题只修了一半……用户不会不可见，但是 icon 会丢掉。
看来工程量有点大 ;)  期待。
