### ISSUE TITLE
1.4.1: meson fails in sphinx-build command

### ISSUE THREAD

**Issue by kloczek** [SrainApp/srain#368]
Meson fails with:
```console
Program sphinx-build found: YES (/usr/bin/sphinx-build)

docs/meson.build:11:2: ERROR: Command "/usr/bin/sphinx-build -b man /home/tkloczko/rpmbuild/BUILD/srain-1.4.1/docs /home/tkloczko/rpmbuild/BUILD/srain-1.4.1/x86_64-redhat-linux-gnu/docs/man" failed with status 2.

A full log can be found at /home/tkloczko/rpmbuild/BUILD/srain-1.4.1/x86_64-redhat-linux-gnu/meson-logs/meson-log.txt
```
In log file it is possible to find:
```console
Running command: /usr/bin/sphinx-build -b man /home/tkloczko/rpmbuild/BUILD/srain-1.4.1/docs /home/tkloczko/rpmbuild/BUILD/srain-1.4.1/x86_64-redhat-linux-gnu/docs/man
--- stdout ---
Running Sphinx v5.1.1

--- stderr ---

Extension error:
Could not import extension sphinxnotes.strike (exception: No module named 'sphinxnotes')
```
- which one exacly module it is? (pypi cannot find `sphinxnotes`)
- Looks like in meson.build is missing line like `import('python').find_installation('python3', modules : ['sphinx',  'sphinxnotes'])`

**Comment by SilverRainZ** [comment]
> which one exactly module it is? (PyPI cannot find sphinxnotes)

The required modules are listed in `docs/requirements.txt`, they are:

```
sphinx-book-theme
ablog
sphinxnotes-strike
sphinxnotes-mock
sphinx_sitemap
sphinxcontrib.gtagjs
sphinxext.opengraph
```

> Looks like in meson.build is missing line like import('python').find_installation('python3', modules : ['sphinx', 'sphinxnotes'])

Yes, hardcoded python command is not good. would you like to file a pull request?

**Comment by kloczek** [comment]
> Yes, hardcoded python command is not good. would you like to file a pull request?

Why not 😄  .. however it would be good to know where I can find `sphinxnotes` to be able test that before create PR 😋

**Comment by kloczek** [comment]
BTW .. is it really necessary to use all those sphinx extensions to create main page? 🤔

**Comment by SilverRainZ** [comment]
> Why not smile .. however it would be good to know where I can find `sphinxnotes` to be able test that before create PR yum

`pip install sphinxnotes-strike sphinxnotes-mock`

**Comment by SilverRainZ** [comment]
> BTW .. is it really necessary to use all those sphinx extensions to create main page? thinking

In fact it is not needed and we can consider not introducing these dependencies when building the manpage.

**Comment by SilverRainZ** [comment]
> which one exacly module it is? (pypi cannot find sphinxnotes)

Does your problem solve after installing the above package?

>  Looks like in meson.build is missing line like import('python').find_installation('python3', modules : ['sphinx', 'sphinxnotes'])

I remove the dependency in https://github.com/SrainApp/srain/pull/370, can you please have a try?

**Comment by SilverRainZ** [comment]
Since Srain documentation does not longer require any extra python package, close this issue.
