### ISSUE TITLE
Move user to existing query tab when clicking Chat entry in user's context menu in channel list

### ISSUE THREAD

**Issue by djasa** [SrainApp/srain#380]
When clicking Chat in context menu, user should be taken to the respective query tab no matter if the tab is already open or not. Currently, srain opens new query tab correctly but when the tab is already open, nothing happens.

Version: 1.4.0/flatpak/flathub @ Fedora 37

**Comment by SilverRainZ** [comment]
I think this is duplicated with https://github.com/SrainApp/srain/issues/381?

**Comment by djasa** [comment]
Uh, it indeed is, sorry.
