### ISSUE TITLE
Possible UI layout ?

### ISSUE THREAD

**Issue by bogdomania** [SrainApp/srain#393]
Hi there,

I was wondering if it's possible to change the UI closer to this ?

![metroIRC dark](https://user-images.githubusercontent.com/46259363/235500190-491ed48c-3ced-4a13-8738-03cb95f9bd12.png)

![metroIRC white](https://user-images.githubusercontent.com/46259363/235500205-32b9f816-50c5-40dc-b27e-0cf5c893b61c.png)

**Comment by SilverRainZ** [comment]
Hello @bogdomania, There is not easy way to change UI layout for GTK application.

**Comment by SilverRainZ** [comment]
As we have no plan to make our UI layout customizable, close it.
