### ISSUE TITLE
Don't auto-append a "-dark" to theme config

### ISSUE THREAD

**Issue by jlo62** [SrainApp/srain#394]
the config line:
``theme = "default-bubble"    # String; Theme; Available values: default``
loads the dark theme, even if I don't use dark theme.

``theme = "default-bubble-dark"    # String; Theme; Available values: default``
gives the error `default-bubble-dark-dark.css was not found` or simular.

**Comment by SilverRainZ** [comment]
"-dark" is automaticlly appeneded only when
- gsetting "gtk-application-prefer-dark-theme" is set to true,.
- or the current theme is a dark theme.

You should not add this dark suffix byself.

**Comment by jlo62** [comment]
well I guess first was true, but I didn't have the second, so it looked horrible and I wanted to change it.
having plasma installed did change pretty much everything. it added the gtk-applications-prefer-dark-theme but I didn't use the dark theme.
Well It makes sense, so nvm.
thx

**Comment by SilverRainZ** [comment]
Can you give me the screenshot? (and what gtk theme are you using?)

**Comment by jlo62** [comment]
![image](https://github.com/SrainApp/srain/assets/122014753/489c6f27-bd47-48d8-843e-0ea130f4b019)
The line in `.config/gtk-3.0/settings.ini`:
``gtk-application-prefer-dark-theme=true``
explains the Behavior.
I tried to change it by appending -dark (result is above), but I fixed it by setting my theme from Adwaita to Adwaita-dark.
now it's resolved itself:
![image](https://github.com/SrainApp/srain/assets/122014753/63a5ec76-2909-4003-989c-4d8817c9535b)
