### ISSUE TITLE
Segfault when trying to log in to a second server once the first has logged in

### ISSUE THREAD

**Issue by areographe** [SrainApp/srain#396]
I have ZNC running on a Raspberry Pi, and I've used the `zncuser/zncnetwork:password` format to authenticate for two different IRC networks.

This means I have two entries n srain's config file, both pointing to the same IP address for the ZNC server, but using different `zncnetwork` values in the format above.

Srain logs in to one network without issue, but trying to connect to the second one causes a crash with the following error:

```

** (srain:105023): WARNING **: 19:39:17.350: (../src/core/message.c:82):srn_message_new: code should not be reached

** (srain:105023): WARNING **: 19:39:17.480: (../src/core/message.c:82):srn_message_new: code should not be reached

** (srain:105023): WARNING **: 19:39:18.043: (../src/core/message.c:82):srn_message_new: code should not be reached

(srain:105023): Gtk-CRITICAL **: 19:40:05.536: gtk_container_remove: assertion 'GTK_IS_WIDGET (widget)' failed
[1]    105023 segmentation fault (core dumped)  srain
```

**Comment by SilverRainZ** [comment]
Thanks for your repot. Can you provide an example config to reproduce this bug?

**Comment by SilverRainZ** [comment]
@areographe I can't reproduce this bug, can you please any steps to reproduce it? (or if you can compile a debug version, please provide a stack trace).

**Comment by progval** [comment]
@areographe additionally, knowing which network is causing the issue would help

**Comment by SilverRainZ** [comment]
No response, close it for now, feel free to reopen it if you suffer the same issue.
