### ISSUE TITLE
Add SaSL authentication

### ISSUE THREAD

**Issue by Agvantibo** [SrainApp/srain#400]
https://ircv3.net/specs/extensions/sasl-3.1

SaSL is pretty much ubiquitous, and as the client lacks an autologin/autoreconnect function, that would fill the niche nicely.

**Comment by SilverRainZ** [comment]
Hi @Agvantibo, Srain [supports both SASL 3.1 and 3.2](https://srain.silverrainz.me/support.html#ircv3-client-support).

I am not sure what "auto-login" and "auto-reconnect" mean. If you have SASL password (stored in secret service) or certificate (stored in config file)specified, Srain will auto-login for you.

**Comment by SilverRainZ** [comment]
No response, close it for now.
