### ISSUE TITLE
log = false not works

### ISSUE THREAD

**Issue by misterhsp** [SrainApp/srain#402]
I have set 'log = false' (chat log) in the srain.cfg. But the chatlog is still written to ~/.local/share/srain/logs. I would like to turn this off.

/hsp

**Comment by SilverRainZ** [comment]
Can you paste your `srain.cfg`?

**Comment by SilverRainZ** [comment]
Sorry, I forgot that this function is not implemented in the code.

https://github.com/SrainApp/srain/blob/7c81bed1cffac7b5ca2aba1d3d287b77d3b1abb1/src/inc/core/chat.h#L72-L79

**Comment by SilverRainZ** [comment]
https://github.com/SrainApp/srain/pull/403 should works, will be released as part of 1.6.0

**Comment by misterhsp** [comment]
meson.build has wrong version

[...]

prooject(
     'srain', 'c',
-   version: '1.5.1',
+  version: '1.6.1',
     license: 'GPL3',
     meson_version: '>= 0.47.0'
)

[...]













Am 11.02.24 um 07:17 schrieb Shengyu Zhang:

**Comment by SilverRainZ** [comment]
@misterhsp thanks for pointing this out. Since it wasn't that long since the release, I recreated the tag
