### ISSUE TITLE
Text is not selectable

### ISSUE THREAD

**Issue by misterhsp** [SrainApp/srain#406]
Message text is not selectable (mouse).

Is this a bug or normal?

/hsp

**Comment by SilverRainZ** [comment]
Message text in the same line should be selectable, what is your version?

**Comment by SilverRainZ** [comment]
Besides, please also provide:

- Version of your DE/WM
- Version of your GTK library
- Your Distro

**Comment by misterhsp** [comment]
Oh sorry, I must have slept a bit or had too much beer :) Yes, of course
it works.



Am 18.02.24 um 03:45 schrieb Shengyu Zhang:
