### ISSUE TITLE
Please port to libsoup-3.0

### ISSUE THREAD

**Issue by bgermann** [SrainApp/srain#409]
Please consider porting from libsoup-2.4 to libsoup-3.0. The older version is currently in the process of being removed from Debian and probably other Linux distributions as well.

**Comment by SilverRainZ** [comment]
Hi @bgermann, I wonder when libsoup-2.4 will be removed from Debian, is there any related issue I can track?

**Comment by bgermann** [comment]
You can track the [bug](https://bugs.debian.org/1056125) or the [transition to libsoup-3.0](https://release.debian.org/transitions/html/libsoup3.html).
