### ISSUE TITLE
Begin with 1.6.0,windows prebuild not work

### ISSUE THREAD

**Issue by iminto** [SrainApp/srain#416]
windows prebuild not work

**Comment by SilverRainZ** [comment]
Hello, please describe "how the prebuild doesn't work", such as missing executable, missing DLL, crash, and so on.

And I am so sorry to say I am not a Windows user so can do nothing with this, I may ask the previous Windows packager for help.

**Comment by iminto** [comment]
> Hello, please describe "how the prebuild doesn't work", such as missing executable, missing DLL, crash, and so on.
> 
> And I am so sorry to say I am not a Windows user so can do nothing with this, I may ask the previous Windows packager for help.

Sorry, I wasn't clear enough.

I'm talking about the action (CI) on this repo, there is an error in the result of the windows prebuild, the final exe file cannot be built, or I cann't find where to download the the executable file of  windows version.
