### ISSUE TITLE
How to enable dark theme?

### ISSUE THREAD

**Issue by RealYukiSan** [SrainApp/srain#422]
I've tried edit file `~/.config/srain/srain.cfg` and `/etc/srain/builtin.cfg` with: `theme = "default-bubble-dark"`

also follow [this comment](https://github.com/SrainApp/srain/issues/291#issuecomment-797150290) and restart the program, but the theme doesn't change, how to fix this?

I've also ensure that file `default-bubble-dark` does exists:

```
$ cat /usr/share/srain/themes/default-bubble-dark.css
@define-color sui_message_list_bg_color1 transparent;
@define-color sui_message_list_bg_color2 transparent;

@define-color sui_message_bg_color alpha(black, 0.4);
@define-color sui_message_shadow_color transparent;

@define-color sui_misc_message_text_color alpha(white, 0.7);
@define-color sui_misc_message_normal_bg_color alpha(black, 0.2);
@define-color sui_misc_message_error_bg_color alpha(#e05868, 0.7);
@define-color sui_misc_message_action_bg_color alpha(#82abe5, 0.7);

@define-color sui_message_counter_text_color alpha(white, 0.7);
@define-color sui_message_counter_bg_color alpha(black, 0.4);
@define-color sui_highlighted_message_counter_bg_color alpha(#e05868, 0.7);

@import url("./default-min.css");
@import url("bubble.css");
```

**Comment by SilverRainZ** [comment]
What desktop environment are you using? Srain respects DE's light/dark settings, please try keeping the config default, and execute  `gsettings set org.gnome.desktop.interface color-scheme prefer-dark`

**Comment by RealYukiSan** [comment]
> What desktop environment are you using?

I'm not using DE, I use DWM

**Comment by RealYukiSan** [comment]
> please try keeping the config default, and execute `gsettings set org.gnome.desktop.interface color-scheme prefer-dark`

```
[hemlo@ASUS ~]$  gsettings get org.gnome.desktop.interface color-scheme
'default'
[hemlo@ASUS ~]$  gsettings set org.gnome.desktop.interface color-scheme prefer-dark
[hemlo@ASUS ~]$ gsettings get org.gnome.desktop.interface color-scheme
'prefer-dark'
```

after restart the app, it's still not applied

**Comment by SilverRainZ** [comment]
Did you restore the config item "theme" to its default value of both system-wide and user-wide config?

**Comment by RealYukiSan** [comment]
> Did you restore the config item "theme" to its default value of both system-wide and user-wide config?

Yes, I did.

the user-wide cfg file by default not exists (or empty? I don't remember), so I remove it.

**Comment by RealYukiSan** [comment]
It seems suspicious that the strain isn’t responding to changes in the system-wide configuration.

**Comment by SilverRainZ** [comment]
Hi @RealYukiSan do you get this issue solved? If so, can you share it with me? if no, you can left this issue opened.

**Comment by RealYukiSan** [comment]
Not at the moment, I will leave this as opened as you suggest.

**Comment by RealYukiSan** [comment]
is this correct for default theme:

```
[Settings]
gtk-theme-name=default-bubble-dark
gtk-icon-theme-name=default-bubble-dark
```

I tried it, but it didn't seem to work.

**Comment by SilverRainZ** [comment]
@RealYukiSan "default-bubble" is Srain's theme, not GTK's theme.

**Comment by RealYukiSan** [comment]
Where can I find one that is installed on my system? Sorry, I am not familiar with GTK

**Comment by SilverRainZ** [comment]
@RealYukiSan You can use theme switcher like lxappearance-gtk3, https://wiki.archlinux.org/title/GTK#Themes may be helpful.

**Comment by RealYukiSan** [comment]
thanks for the link, seems the problem is, by default on my system, the gtk theme using Adwaita:
``` 
$ gsettings get org.gnome.desktop.interface gtk-theme
'Adwaita'
```

and the Adwaita theme was provided by `[gnome-themes-extra](https://archlinux.org/packages/?name=gnome-themes-extra)` package which I not installed on my system.

it works as expected after installing the package.
